/**
 * This class is generated by jOOQ
 */
package com.ie.entities.dev_ie_arm.tables;


import com.ie.entities.dev_ie_arm.DevIeArm;
import com.ie.entities.dev_ie_arm.Keys;
import com.ie.entities.dev_ie_arm.tables.records.ExtrachargeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Extracharge extends TableImpl<ExtrachargeRecord> {

	private static final long serialVersionUID = -774449231;

	/**
	 * The reference instance of <code>dev_ie_arm.Extracharge</code>
	 */
	public static final Extracharge EXTRACHARGE = new Extracharge();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ExtrachargeRecord> getRecordType() {
		return ExtrachargeRecord.class;
	}

	/**
	 * The column <code>dev_ie_arm.Extracharge.id</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.created</code>.
	 */
	public static final TableField<ExtrachargeRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.amount</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.days</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> DAYS = createField("days", org.jooq.impl.SQLDataType.INTEGER, EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.invoice</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> INVOICE = createField("invoice", org.jooq.impl.SQLDataType.INTEGER, EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.rroId</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> RROID = createField("rroId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.tariff</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> TARIFF = createField("tariff", org.jooq.impl.SQLDataType.INTEGER.nullable(false), EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.rroLink</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> RROLINK = createField("rroLink", org.jooq.impl.SQLDataType.INTEGER.nullable(false), EXTRACHARGE, "");

	/**
	 * The column <code>dev_ie_arm.Extracharge.scId</code>.
	 */
	public static final TableField<ExtrachargeRecord, Integer> SCID = createField("scId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), EXTRACHARGE, "");

	/**
	 * No further instances allowed
	 */
	private Extracharge() {
		this("Extracharge", null);
	}

	private Extracharge(String alias, Table<ExtrachargeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Extracharge(String alias, Table<ExtrachargeRecord> aliased, Field<?>[] parameters) {
		super(alias, DevIeArm.DEV_IE_ARM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ExtrachargeRecord, Integer> getIdentity() {
		return Keys.IDENTITY_EXTRACHARGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ExtrachargeRecord> getPrimaryKey() {
		return Keys.KEY_EXTRACHARGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ExtrachargeRecord>> getKeys() {
		return Arrays.<UniqueKey<ExtrachargeRecord>>asList(Keys.KEY_EXTRACHARGE_PRIMARY);
	}
}
