/**
 * This class is generated by jOOQ
 */
package com.ie.entities.dev_ie_arm.tables;


import com.ie.entities.dev_ie_arm.DevIeArm;
import com.ie.entities.dev_ie_arm.Keys;
import com.ie.entities.dev_ie_arm.tables.records.RroRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rro extends TableImpl<RroRecord> {

	private static final long serialVersionUID = 200181721;

	/**
	 * The reference instance of <code>dev_ie_arm.Rro</code>
	 */
	public static final Rro RRO = new Rro();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RroRecord> getRecordType() {
		return RroRecord.class;
	}

	/**
	 * The column <code>dev_ie_arm.Rro.id</code>.
	 */
	public static final TableField<RroRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.changed</code>.
	 */
	public static final TableField<RroRecord, Timestamp> CHANGED = createField("changed", org.jooq.impl.SQLDataType.TIMESTAMP, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.created</code>.
	 */
	public static final TableField<RroRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.deleted</code>.
	 */
	public static final TableField<RroRecord, Timestamp> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TIMESTAMP, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.description</code>.
	 */
	public static final TableField<RroRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.firstPersonalized</code>.
	 */
	public static final TableField<RroRecord, Timestamp> FIRSTPERSONALIZED = createField("firstPersonalized", org.jooq.impl.SQLDataType.TIMESTAMP, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.fiscNum</code>.
	 */
	public static final TableField<RroRecord, Long> FISCNUM = createField("fiscNum", org.jooq.impl.SQLDataType.BIGINT.nullable(false), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.lastError</code>.
	 */
	public static final TableField<RroRecord, Timestamp> LASTERROR = createField("lastError", org.jooq.impl.SQLDataType.TIMESTAMP, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.lastReceived</code>.
	 */
	public static final TableField<RroRecord, Timestamp> LASTRECEIVED = createField("lastReceived", org.jooq.impl.SQLDataType.TIMESTAMP, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.lastStatusChangging</code>.
	 */
	public static final TableField<RroRecord, Timestamp> LASTSTATUSCHANGGING = createField("lastStatusChangging", org.jooq.impl.SQLDataType.TIMESTAMP, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.status</code>.
	 */
	public static final TableField<RroRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(12), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.сomment</code>.
	 */
	public static final TableField<RroRecord, String> СOMMENT = createField("сomment", org.jooq.impl.SQLDataType.VARCHAR.length(255), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.changedById</code>.
	 */
	public static final TableField<RroRecord, Integer> CHANGEDBYID = createField("changedById", org.jooq.impl.SQLDataType.INTEGER, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.activeDevice</code>.
	 */
	public static final TableField<RroRecord, Long> ACTIVEDEVICE = createField("activeDevice", org.jooq.impl.SQLDataType.BIGINT.nullable(false), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.activeTariff</code>.
	 */
	public static final TableField<RroRecord, Integer> ACTIVETARIFF = createField("activeTariff", org.jooq.impl.SQLDataType.INTEGER.nullable(false), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.modelId</code>.
	 */
	public static final TableField<RroRecord, Integer> MODELID = createField("modelId", org.jooq.impl.SQLDataType.INTEGER, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.activeRroLink</code>.
	 */
	public static final TableField<RroRecord, Integer> ACTIVERROLINK = createField("activeRroLink", org.jooq.impl.SQLDataType.INTEGER, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.RroModelId</code>.
	 */
	public static final TableField<RroRecord, Integer> RROMODELID = createField("RroModelId", org.jooq.impl.SQLDataType.INTEGER, RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.rroMaster</code>.
	 */
	public static final TableField<RroRecord, String> RROMASTER = createField("rroMaster", org.jooq.impl.SQLDataType.VARCHAR.length(50), RRO, "");

	/**
	 * The column <code>dev_ie_arm.Rro.serialNo</code>.
	 */
	public static final TableField<RroRecord, String> SERIALNO = createField("serialNo", org.jooq.impl.SQLDataType.VARCHAR.length(50), RRO, "");

	/**
	 * No further instances allowed
	 */
	private Rro() {
		this("Rro", null);
	}

	private Rro(String alias, Table<RroRecord> aliased) {
		this(alias, aliased, null);
	}

	private Rro(String alias, Table<RroRecord> aliased, Field<?>[] parameters) {
		super(alias, DevIeArm.DEV_IE_ARM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RroRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RroRecord> getPrimaryKey() {
		return Keys.KEY_RRO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RroRecord>> getKeys() {
		return Arrays.<UniqueKey<RroRecord>>asList(Keys.KEY_RRO_PRIMARY, Keys.KEY_RRO_FISCNUM_UNIQUE);
	}
}
