/**
 * This class is generated by jOOQ
 */
package com.ie.entities.dev_ie_arm;


import com.ie.entities.dev_ie_arm.tables.Device;
import com.ie.entities.dev_ie_arm.tables.Extracharge;
import com.ie.entities.dev_ie_arm.tables.Rro;
import com.ie.entities.dev_ie_arm.tables.Servicecenter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevIeArm extends SchemaImpl {

	private static final long serialVersionUID = -2120613491;

	/**
	 * The reference instance of <code>dev_ie_arm</code>
	 */
	public static final DevIeArm DEV_IE_ARM = new DevIeArm();

	/**
	 * No further instances allowed
	 */
	private DevIeArm() {
		super("dev_ie_arm");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Device.DEVICE,
			Extracharge.EXTRACHARGE,
			Rro.RRO,
			Servicecenter.SERVICECENTER);
	}
}
