/**
 * This class is generated by jOOQ
 */
package com.ie.entities.dev_ie_arm;


import com.ie.entities.dev_ie_arm.tables.Device;
import com.ie.entities.dev_ie_arm.tables.Extracharge;
import com.ie.entities.dev_ie_arm.tables.Rro;
import com.ie.entities.dev_ie_arm.tables.Servicecenter;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dev_ie_arm
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table dev_ie_arm.Device
	 */
	public static final Device DEVICE = com.ie.entities.dev_ie_arm.tables.Device.DEVICE;

	/**
	 * The table dev_ie_arm.Extracharge
	 */
	public static final Extracharge EXTRACHARGE = com.ie.entities.dev_ie_arm.tables.Extracharge.EXTRACHARGE;

	/**
	 * The table dev_ie_arm.Rro
	 */
	public static final Rro RRO = com.ie.entities.dev_ie_arm.tables.Rro.RRO;

	/**
	 * The table dev_ie_arm.ServiceCenter
	 */
	public static final Servicecenter SERVICECENTER = com.ie.entities.dev_ie_arm.tables.Servicecenter.SERVICECENTER;
}
