/**
 * This class is generated by jOOQ
 */
package com.ie.entities.dev_ie_arm.tables.records;


import com.ie.entities.dev_ie_arm.tables.Extracharge;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExtrachargeRecord extends UpdatableRecordImpl<ExtrachargeRecord> implements Record9<Integer, Timestamp, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = -1824103097;

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.created</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.created</code>.
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.amount</code>.
	 */
	public void setAmount(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.amount</code>.
	 */
	public Integer getAmount() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.days</code>.
	 */
	public void setDays(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.days</code>.
	 */
	public Integer getDays() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.invoice</code>.
	 */
	public void setInvoice(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.invoice</code>.
	 */
	public Integer getInvoice() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.rroId</code>.
	 */
	public void setRroid(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.rroId</code>.
	 */
	public Integer getRroid() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.tariff</code>.
	 */
	public void setTariff(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.tariff</code>.
	 */
	public Integer getTariff() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.rroLink</code>.
	 */
	public void setRrolink(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.rroLink</code>.
	 */
	public Integer getRrolink() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>dev_ie_arm.Extracharge.scId</code>.
	 */
	public void setScid(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Extracharge.scId</code>.
	 */
	public Integer getScid() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Timestamp, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, Timestamp, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Extracharge.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Extracharge.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Extracharge.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Extracharge.DAYS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Extracharge.INVOICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Extracharge.RROID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Extracharge.TARIFF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Extracharge.RROLINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Extracharge.SCID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getDays();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getInvoice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getRroid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getTariff();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getRrolink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getScid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value2(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value3(Integer value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value4(Integer value) {
		setDays(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value5(Integer value) {
		setInvoice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value6(Integer value) {
		setRroid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value7(Integer value) {
		setTariff(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value8(Integer value) {
		setRrolink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord value9(Integer value) {
		setScid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ExtrachargeRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ExtrachargeRecord
	 */
	public ExtrachargeRecord() {
		super(Extracharge.EXTRACHARGE);
	}

	/**
	 * Create a detached, initialised ExtrachargeRecord
	 */
	public ExtrachargeRecord(Integer id, Timestamp created, Integer amount, Integer days, Integer invoice, Integer rroid, Integer tariff, Integer rrolink, Integer scid) {
		super(Extracharge.EXTRACHARGE);

		setValue(0, id);
		setValue(1, created);
		setValue(2, amount);
		setValue(3, days);
		setValue(4, invoice);
		setValue(5, rroid);
		setValue(6, tariff);
		setValue(7, rrolink);
		setValue(8, scid);
	}
}
