/**
 * This class is generated by jOOQ
 */
package com.ie.entities.dev_ie_arm.tables.records;


import com.ie.entities.dev_ie_arm.tables.Rro;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RroRecord extends UpdatableRecordImpl<RroRecord> implements Record20<Integer, Timestamp, Timestamp, Timestamp, String, Timestamp, Long, Timestamp, Timestamp, Timestamp, String, String, Integer, Long, Integer, Integer, Integer, Integer, String, String> {

	private static final long serialVersionUID = 2095914281;

	/**
	 * Setter for <code>dev_ie_arm.Rro.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.changed</code>.
	 */
	public void setChanged(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.changed</code>.
	 */
	public Timestamp getChanged() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.created</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.created</code>.
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.deleted</code>.
	 */
	public void setDeleted(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.deleted</code>.
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.description</code>.
	 */
	public void setDescription(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.firstPersonalized</code>.
	 */
	public void setFirstpersonalized(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.firstPersonalized</code>.
	 */
	public Timestamp getFirstpersonalized() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.fiscNum</code>.
	 */
	public void setFiscnum(Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.fiscNum</code>.
	 */
	public Long getFiscnum() {
		return (Long) getValue(6);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.lastError</code>.
	 */
	public void setLasterror(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.lastError</code>.
	 */
	public Timestamp getLasterror() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.lastReceived</code>.
	 */
	public void setLastreceived(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.lastReceived</code>.
	 */
	public Timestamp getLastreceived() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.lastStatusChangging</code>.
	 */
	public void setLaststatuschangging(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.lastStatusChangging</code>.
	 */
	public Timestamp getLaststatuschangging() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.status</code>.
	 */
	public void setStatus(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.сomment</code>.
	 */
	public void setСomment(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.сomment</code>.
	 */
	public String getСomment() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.changedById</code>.
	 */
	public void setChangedbyid(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.changedById</code>.
	 */
	public Integer getChangedbyid() {
		return (Integer) getValue(12);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.activeDevice</code>.
	 */
	public void setActivedevice(Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.activeDevice</code>.
	 */
	public Long getActivedevice() {
		return (Long) getValue(13);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.activeTariff</code>.
	 */
	public void setActivetariff(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.activeTariff</code>.
	 */
	public Integer getActivetariff() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.modelId</code>.
	 */
	public void setModelid(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.modelId</code>.
	 */
	public Integer getModelid() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.activeRroLink</code>.
	 */
	public void setActiverrolink(Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.activeRroLink</code>.
	 */
	public Integer getActiverrolink() {
		return (Integer) getValue(16);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.RroModelId</code>.
	 */
	public void setRromodelid(Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.RroModelId</code>.
	 */
	public Integer getRromodelid() {
		return (Integer) getValue(17);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.rroMaster</code>.
	 */
	public void setRromaster(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.rroMaster</code>.
	 */
	public String getRromaster() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>dev_ie_arm.Rro.serialNo</code>.
	 */
	public void setSerialno(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>dev_ie_arm.Rro.serialNo</code>.
	 */
	public String getSerialno() {
		return (String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row20<Integer, Timestamp, Timestamp, Timestamp, String, Timestamp, Long, Timestamp, Timestamp, Timestamp, String, String, Integer, Long, Integer, Integer, Integer, Integer, String, String> fieldsRow() {
		return (Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row20<Integer, Timestamp, Timestamp, Timestamp, String, Timestamp, Long, Timestamp, Timestamp, Timestamp, String, String, Integer, Long, Integer, Integer, Integer, Integer, String, String> valuesRow() {
		return (Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Rro.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Rro.CHANGED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Rro.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Rro.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Rro.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Rro.FIRSTPERSONALIZED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field7() {
		return Rro.FISCNUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return Rro.LASTERROR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Rro.LASTRECEIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return Rro.LASTSTATUSCHANGGING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return Rro.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return Rro.СOMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Rro.CHANGEDBYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field14() {
		return Rro.ACTIVEDEVICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return Rro.ACTIVETARIFF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return Rro.MODELID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field17() {
		return Rro.ACTIVERROLINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field18() {
		return Rro.RROMODELID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field19() {
		return Rro.RROMASTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field20() {
		return Rro.SERIALNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getChanged();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getFirstpersonalized();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value7() {
		return getFiscnum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getLasterror();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getLastreceived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getLaststatuschangging();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getСomment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getChangedbyid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value14() {
		return getActivedevice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getActivetariff();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getModelid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value17() {
		return getActiverrolink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value18() {
		return getRromodelid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value19() {
		return getRromaster();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value20() {
		return getSerialno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value2(Timestamp value) {
		setChanged(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value3(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value4(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value5(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value6(Timestamp value) {
		setFirstpersonalized(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value7(Long value) {
		setFiscnum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value8(Timestamp value) {
		setLasterror(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value9(Timestamp value) {
		setLastreceived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value10(Timestamp value) {
		setLaststatuschangging(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value11(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value12(String value) {
		setСomment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value13(Integer value) {
		setChangedbyid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value14(Long value) {
		setActivedevice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value15(Integer value) {
		setActivetariff(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value16(Integer value) {
		setModelid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value17(Integer value) {
		setActiverrolink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value18(Integer value) {
		setRromodelid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value19(String value) {
		setRromaster(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord value20(String value) {
		setSerialno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RroRecord values(Integer value1, Timestamp value2, Timestamp value3, Timestamp value4, String value5, Timestamp value6, Long value7, Timestamp value8, Timestamp value9, Timestamp value10, String value11, String value12, Integer value13, Long value14, Integer value15, Integer value16, Integer value17, Integer value18, String value19, String value20) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		value20(value20);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RroRecord
	 */
	public RroRecord() {
		super(Rro.RRO);
	}

	/**
	 * Create a detached, initialised RroRecord
	 */
	public RroRecord(Integer id, Timestamp changed, Timestamp created, Timestamp deleted, String description, Timestamp firstpersonalized, Long fiscnum, Timestamp lasterror, Timestamp lastreceived, Timestamp laststatuschangging, String status, String сomment, Integer changedbyid, Long activedevice, Integer activetariff, Integer modelid, Integer activerrolink, Integer rromodelid, String rromaster, String serialno) {
		super(Rro.RRO);

		setValue(0, id);
		setValue(1, changed);
		setValue(2, created);
		setValue(3, deleted);
		setValue(4, description);
		setValue(5, firstpersonalized);
		setValue(6, fiscnum);
		setValue(7, lasterror);
		setValue(8, lastreceived);
		setValue(9, laststatuschangging);
		setValue(10, status);
		setValue(11, сomment);
		setValue(12, changedbyid);
		setValue(13, activedevice);
		setValue(14, activetariff);
		setValue(15, modelid);
		setValue(16, activerrolink);
		setValue(17, rromodelid);
		setValue(18, rromaster);
		setValue(19, serialno);
	}
}
